"use client";

import { useRoutineStore, RoutineTemplate } from "@/store/useRoutineStore";
import { ChevronLeft, Library, Check, X, Download, AlertTriangle, Plus, Trash2, Save, Share } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { GoalType, SplitType } from "@/lib/ixia-ai";
import { IxiaLoadingState } from "@/components/IxiaLoadingState";
import Orb from "@/components/Orb";
import { toast } from "react-hot-toast";

export default function TemplatesPage() {
  const { 
    templates, 
    customTemplates = [], 
    weeklyPlan, 
    loadTemplate, 
    applyAiRoutine, 
    exportRoutine,
    saveCustomTemplate,
    deleteCustomTemplate
  } = useRoutineStore();
  
  const router = useRouter();
  const [activeTab, setActiveTab] = useState<"my-plans" | "explore">("my-plans");
  const [appliedId, setAppliedId] = useState<string | null>(null);
  const [selectedViewTemplate, setSelectedViewTemplate] = useState<RoutineTemplate | null>(null);
  const [activeViewDay, setActiveViewDay] = useState<string>("Monday");

  // iXiA AI Modal State
  const [showAiModal, setShowAiModal] = useState(false);
  const [goal, setGoal] = useState<GoalType>('hypertrophy');
  const [split, setSplit] = useState<SplitType>('ppl');
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Confirmation state for AI
  const [isConfirming, setIsConfirming] = useState(false);
  const [generatedPlan, setGeneratedPlan] = useState<any>(null);
  
  // AI Save naming sub-view state
  const [ixiaSaveMode, setIxiaSaveMode] = useState(false);
  const [ixiaTemplateName, setIxiaTemplateName] = useState("");
  const [ixiaTemplateDesc, setIxiaTemplateDesc] = useState("");
  const [shouldDownloadBackup, setShouldDownloadBackup] = useState(false);

  // Save current active split modal state
  const [showSaveActiveModal, setShowSaveActiveModal] = useState(false);
  const [activeTemplateName, setActiveTemplateName] = useState("");
  const [activeTemplateDesc, setActiveTemplateDesc] = useState("");

  const handleApplyTemplate = (id: string) => {
    loadTemplate(id);
    setAppliedId(id);
    toast.success("Routine applied successfully!");
    setTimeout(() => {
      router.push("/routines");
    }, 800);
  };

  const handleGenerateAi = async () => {
    setIsGenerating(true);
    try {
      const res = await fetch('/api/ai/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ goal, split })
      });
      
      if (!res.ok) {
        throw new Error('Failed to generate routine from AI');
      }
      
      const data = await res.json();
      if (data.plan) {
        setGeneratedPlan(data.plan);
        setIsGenerating(false);
        setIsConfirming(true);
        setIxiaSaveMode(false);
        setIxiaTemplateName(`iXiA ${goal.charAt(0).toUpperCase() + goal.slice(1)} ${split.toUpperCase()}`);
        setIxiaTemplateDesc(`Custom routine generated by iXiA AI on ${new Date().toLocaleDateString()}`);
      } else {
        throw new Error('Invalid response structure');
      }
    } catch (error) {
      console.error('Error generating AI routine:', error);
      setIsGenerating(false);
      toast.error("Failed to generate AI routine. Please try again.");
    }
  };

  const triggerBackupDownload = () => {
    const base64Str = exportRoutine();
    if (base64Str) {
      const element = document.createElement("a");
      element.href = "data:text/plain;charset=utf-8," + encodeURIComponent(base64Str);
      element.download = `vortixia_routine_backup_${new Date().toISOString().slice(0,10)}.txt`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    }
  };

  const handleApplyAiDirectly = () => {
    if (shouldDownloadBackup) {
      triggerBackupDownload();
    }
    if (generatedPlan) {
      applyAiRoutine(generatedPlan);
    }
    setShowAiModal(false);
    setIsConfirming(false);
    toast.success("AI Routine applied to active split!");
    router.push("/routines");
  };

  const handleSaveAiTemplate = (applyAfterSaving: boolean) => {
    if (!ixiaTemplateName.trim()) {
      toast.error("Please enter a template name.");
      return;
    }

    const success = saveCustomTemplate(ixiaTemplateName, ixiaTemplateDesc, generatedPlan);
    if (success) {
      toast.success("Routine saved to My Plans!");
      if (applyAfterSaving) {
        if (shouldDownloadBackup) {
          triggerBackupDownload();
        }
        applyAiRoutine(generatedPlan);
        toast.success("Routine applied as active split!");
        setShowAiModal(false);
        setIsConfirming(false);
        router.push("/routines");
      } else {
        setShowAiModal(false);
        setIsConfirming(false);
      }
    } else {
      toast.error("Limit reached: You can save up to 15 custom templates.");
    }
  };

  const handleSaveActiveTemplate = () => {
    if (!activeTemplateName.trim()) {
      toast.error("Please enter a name for your split.");
      return;
    }

    const success = saveCustomTemplate(activeTemplateName, activeTemplateDesc, weeklyPlan);
    if (success) {
      toast.success("Active routine saved to templates!");
      setShowSaveActiveModal(false);
      setActiveTemplateName("");
      setActiveTemplateDesc("");
    } else {
      toast.error("Limit reached: You can save up to 15 custom templates.");
    }
  };

  const handleDeleteCustom = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    if (confirm("Are you sure you want to delete this custom template?")) {
      deleteCustomTemplate(id);
      toast.success("Template deleted.");
    }
  };

  const handleExportCustom = (e: React.MouseEvent, tpl: any) => {
    e.stopPropagation();
    try {
      const jsonStr = JSON.stringify(tpl.plan);
      const base64Str = btoa(encodeURIComponent(jsonStr));
      
      const element = document.createElement("a");
      element.href = "data:text/plain;charset=utf-8," + encodeURIComponent(base64Str);
      element.download = `${tpl.name.toLowerCase().replace(/\s+/g, '_')}_backup.txt`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
      toast.success("Template downloaded!");
    } catch (err) {
      toast.error("Failed to export template.");
    }
  };

  return (
    <main className="flex min-h-screen flex-col pb-28 px-6 bg-[#050505] relative overflow-x-hidden">
      
      <header className="w-full flex items-center justify-between pt-[calc(var(--notch-top)+1rem)] pb-4 mb-2 sticky top-0 z-20 bg-[#050505]/80 backdrop-blur-lg">
        <div className="flex items-center gap-4">
          <Link href="/routines" className="p-2 bg-white/5 rounded-full border border-white/10 hover:bg-white/10 transition-colors" aria-label="Go back">
            <ChevronLeft className="w-5 h-5 text-white" />
          </Link>
          <div className="flex flex-col">
            <h1 className="text-2xl font-extrabold tracking-tight text-white">Templates</h1>
            <span className="text-[10px] text-accent-green uppercase font-bold tracking-widest">Library</span>
          </div>
        </div>
      </header>

      {/* iXiA AI Premium Button */}
      <button 
        onClick={() => {
          setShowAiModal(true);
          setIsConfirming(false);
          setGeneratedPlan(null);
        }}
        className="w-full relative group overflow-hidden rounded-3xl p-6 border border-[#2EEA82]/40 bg-gradient-to-br from-[#0a1a12] to-[#050505] flex flex-col items-center justify-center gap-3 mb-6 animate-fade-in-up shadow-[0_0_30px_rgba(46,234,130,0.15)] transition-transform active:scale-95"
      >
        <div className="absolute inset-0 bg-gradient-to-r from-[#2EEA82]/0 via-[#2EEA82]/20 to-[#2EEA82]/0 translate-x-[-100%] group-hover:animate-[shimmer_2s_infinite]" />
        
        {/* Breathing Orb inside Button */}
        <div className="relative flex items-center justify-center mb-2 w-16 h-16 pointer-events-none">
           <Orb hoverIntensity={0.2} rotateOnHover={true} forceHoverState={true} backgroundColor="transparent" />
        </div>
        
        <div className="flex flex-col items-center">
          <span className="text-lg font-black text-white tracking-widest uppercase shadow-black drop-shadow-md">iXiA Ai Generator</span>
          <span className="text-xs text-[#2EEA82]/80 font-medium">Auto-build your perfect routine</span>
        </div>
      </button>

      {/* Navigation Tabs */}
      <div className="flex bg-black/50 p-1 rounded-2xl border border-white/5 mb-6 animate-fade-in-up">
        <button
          onClick={() => setActiveTab("my-plans")}
          className={`flex-1 py-3 text-xs font-black uppercase tracking-widest rounded-xl transition-all ${
            activeTab === "my-plans" ? "bg-white/10 text-white shadow-sm" : "text-text-muted hover:text-white"
          }`}
        >
          My Plans
        </button>
        <button
          onClick={() => setActiveTab("explore")}
          className={`flex-1 py-3 text-xs font-black uppercase tracking-widest rounded-xl transition-all ${
            activeTab === "explore" ? "bg-white/10 text-white shadow-sm" : "text-text-muted hover:text-white"
          }`}
        >
          Explore
        </button>
      </div>

      {/* Tab Contents */}
      {activeTab === "explore" ? (
        <section className="flex flex-col gap-4 animate-fade-in-up">
          {templates.map((tpl) => (
            <div key={tpl.id} className="glass-card p-5 relative overflow-hidden group border border-white/5">
              <div className="flex items-start justify-between relative z-10">
                <div className="flex flex-col">
                  <h2 className="text-lg font-black text-white">{tpl.name}</h2>
                  <span className="text-[10px] uppercase font-bold text-accent-green tracking-widest mt-1">{tpl.frequency}</span>
                </div>
                <Library className="w-6 h-6 text-white/20" />
              </div>
              
              <p className="text-xs text-text-muted mt-3 relative z-10 pr-4">
                {tpl.description}
              </p>

              <div className="flex gap-3 mt-5">
                <button
                  onClick={() => {
                    setSelectedViewTemplate(tpl);
                    setActiveViewDay(tpl.plan[0]?.day || "Monday");
                  }}
                  className="flex-1 py-3 rounded-xl font-bold text-xs tracking-wider bg-white/5 hover:bg-white/10 text-white border border-white/5 transition-all"
                >
                  VIEW WORKOUT
                </button>
                <button
                  onClick={() => handleApplyTemplate(tpl.id)}
                  disabled={appliedId !== null}
                  className={`flex-1 py-3 rounded-xl font-bold text-xs tracking-wider transition-all ${
                    appliedId === tpl.id 
                      ? 'bg-accent-green text-black' 
                      : 'bg-white/10 text-white hover:bg-white/20 border border-white/5'
                  }`}
                >
                  {appliedId === tpl.id ? (
                    <span className="flex items-center justify-center gap-2">
                      <Check className="w-4 h-4" /> APPLIED
                    </span>
                  ) : (
                    "APPLY TEMPLATE"
                  )}
                </button>
              </div>
            </div>
          ))}
        </section>
      ) : (
        <section className="flex flex-col gap-4 animate-fade-in-up">
          
          <button
            onClick={() => {
              setActiveTemplateName("My Custom Split");
              setActiveTemplateDesc(`Created on ${new Date().toLocaleDateString()}`);
              setShowSaveActiveModal(true);
            }}
            className="w-full py-4 border border-dashed border-white/10 hover:border-white/20 bg-white/5 hover:bg-white/10 rounded-2xl text-white font-bold text-xs uppercase tracking-widest transition-all flex items-center justify-center gap-2"
          >
            <Plus className="w-4 h-4 text-accent-green" /> Save Current Split as Template
          </button>

          <div className="flex justify-between items-center px-1">
            <span className="text-[10px] text-text-muted font-bold uppercase tracking-wider">Saved Routines</span>
            <span className="text-[10px] text-text-muted font-bold uppercase tracking-wider">{customTemplates.length} / 15 saved</span>
          </div>

          {customTemplates.length === 0 ? (
            <div className="glass-card p-8 text-center border border-white/5 flex flex-col items-center justify-center">
              <span className="text-sm font-bold text-text-muted mb-1">No custom templates</span>
              <span className="text-xs text-text-muted/60 max-w-[200px]">Save your current routine or build one using the iXiA AI Generator.</span>
            </div>
          ) : (
            customTemplates.map((tpl) => (
              <div key={tpl.id} className="glass-card p-5 relative overflow-hidden group border border-white/5 flex flex-col">
                <div className="flex items-start justify-between relative z-10">
                  <div className="flex flex-col">
                    <h2 className="text-lg font-black text-white">{tpl.name}</h2>
                    <span className="text-[10px] uppercase font-bold text-accent-green tracking-widest mt-1">{tpl.frequency}</span>
                  </div>
                  <div className="flex gap-2">
                    <button 
                      onClick={(e) => handleExportCustom(e, tpl)}
                      aria-label="Export Template"
                      className="p-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-full text-text-muted hover:text-white transition"
                    >
                      <Share className="w-4 h-4" />
                    </button>
                    <button 
                      onClick={(e) => handleDeleteCustom(e, tpl.id)}
                      aria-label="Delete Template"
                      className="p-2 bg-red-500/10 hover:bg-red-500/20 border border-red-500/20 rounded-full text-red-400 hover:text-red-300 transition"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </div>
                
                <p className="text-xs text-text-muted mt-3 relative z-10 pr-4">
                  {tpl.description}
                </p>

                <div className="flex gap-3 mt-5">
                  <button
                    onClick={() => {
                      setSelectedViewTemplate(tpl);
                      setActiveViewDay(tpl.plan[0]?.day || "Monday");
                    }}
                    className="flex-1 py-3 rounded-xl font-bold text-xs tracking-wider bg-white/5 hover:bg-white/10 text-white border border-white/5 transition-all"
                  >
                    VIEW WORKOUT
                  </button>
                  <button
                    onClick={() => handleApplyTemplate(tpl.id)}
                    disabled={appliedId !== null}
                    className={`flex-1 py-3 rounded-xl font-bold text-xs tracking-wider transition-all ${
                      appliedId === tpl.id 
                        ? 'bg-accent-green text-black' 
                        : 'bg-white/10 text-white hover:bg-white/20 border border-white/5'
                    }`}
                  >
                    {appliedId === tpl.id ? (
                      <span className="flex items-center justify-center gap-2">
                        <Check className="w-4 h-4" /> APPLIED
                      </span>
                    ) : (
                      "APPLY TEMPLATE"
                    )}
                  </button>
                </div>
              </div>
            ))
          )}
        </section>
      )}

      {/* Save Active Split Modal */}
      {showSaveActiveModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in">
          <div className="w-full max-w-sm bg-[#111] border border-white/10 rounded-[2rem] p-6 relative animate-fade-in-up">
            <button 
              onClick={() => setShowSaveActiveModal(false)}
              className="absolute top-4 right-4 p-2 bg-white/5 rounded-full hover:bg-white/10 text-text-muted hover:text-white"
            >
              <X className="w-4 h-4" />
            </button>
            <h3 className="text-lg font-black text-white mb-2 flex items-center gap-2">
              <Save className="w-5 h-5 text-accent-green" />
              Save to My Plans
            </h3>
            <p className="text-xs text-text-muted mb-4">Give your active split a name and description to save it locally.</p>
            
            <div className="flex flex-col gap-4">
              <div className="flex flex-col gap-1">
                <label className="text-[10px] uppercase font-bold text-accent-green tracking-wider ml-1">Template Name</label>
                <input 
                  type="text" 
                  value={activeTemplateName}
                  onChange={(e) => setActiveTemplateName(e.target.value)}
                  placeholder="e.g. My Summer Split"
                  maxLength={50}
                  className="w-full bg-black border border-white/10 rounded-xl p-3 text-white text-sm outline-none focus:border-accent-green"
                />
              </div>
              
              <div className="flex flex-col gap-1">
                <label className="text-[10px] uppercase font-bold text-accent-green tracking-wider ml-1">Description (Optional)</label>
                <textarea 
                  value={activeTemplateDesc}
                  onChange={(e) => setActiveTemplateDesc(e.target.value)}
                  placeholder="e.g. 5-day hyper split focused on shoulders"
                  maxLength={150}
                  className="w-full bg-black border border-white/10 rounded-xl p-3 text-white text-sm outline-none focus:border-accent-green h-20 resize-none"
                />
              </div>
              
              <button 
                onClick={handleSaveActiveTemplate}
                className="w-full py-4 mt-2 bg-accent-green text-black font-black text-xs uppercase tracking-widest rounded-xl transition-all active:scale-95 shadow-lg"
              >
                SAVE TEMPLATE
              </button>
            </div>
          </div>
        </div>
      )}

      {/* iXiA AI Modal */}
      {showAiModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/90 backdrop-blur-xl animate-fade-in">
          <div className="w-full max-w-sm bg-[#050505] border border-white/10 rounded-[2rem] overflow-hidden relative shadow-[0_0_50px_rgba(46,234,130,0.1)]">
            
            <div className="absolute top-0 left-0 w-full h-1/2 bg-gradient-to-b from-[#2EEA82]/10 to-transparent pointer-events-none" />

            {isGenerating ? (
              <IxiaLoadingState />
            ) : isConfirming ? (
              <div className="p-8 flex flex-col items-center text-center animate-fade-in-up max-h-[85vh] overflow-y-auto">
                <button 
                  onClick={() => setShowAiModal(false)}
                  className="absolute top-4 right-4 p-2 bg-white/5 rounded-full hover:bg-white/10 z-10 text-text-muted hover:text-white"
                >
                  <X className="w-4 h-4" />
                </button>
                <div className="relative mb-6 mt-4 pointer-events-none">
                  <div className="w-20 h-20">
                    <Orb hoverIntensity={0.8} rotateOnHover={true} forceHoverState={true} backgroundColor="transparent" />
                  </div>
                </div>
                
                <h2 className="text-2xl font-black text-white mb-2">iXiA Split Built!</h2>

                {!ixiaSaveMode ? (
                  <>
                    <p className="text-xs text-text-muted mb-5 leading-relaxed max-w-[280px]">
                      Your AI routine is ready. You can apply it directly to your weekly split, or save it to your plans.
                    </p>

                    <div className="w-full bg-[#111] border border-white/5 rounded-2xl p-4 mb-5 text-left">
                      <label className="flex items-center gap-3 cursor-pointer select-none">
                        <input 
                          type="checkbox" 
                          checked={shouldDownloadBackup} 
                          onChange={(e) => setShouldDownloadBackup(e.target.checked)}
                          className="w-4 h-4 accent-accent-green"
                        />
                        <div className="flex flex-col">
                          <span className="text-xs font-bold text-white">Download Active Split Backup</span>
                          <span className="text-[9px] text-text-muted">Export current plan as .txt file first</span>
                        </div>
                      </label>
                    </div>

                    <div className="flex flex-col gap-3 w-full">
                      <button
                        onClick={() => setIxiaSaveMode(true)}
                        className="w-full bg-[#2EEA82] text-black font-black text-xs uppercase tracking-widest py-4 rounded-xl hover:bg-[#2ae07b] transition-all flex items-center justify-center gap-2 shadow-lg"
                      >
                        <Plus className="w-4 h-4 stroke-[3px]" /> Save to My Plans
                      </button>
                      
                      <button
                        onClick={handleApplyAiDirectly}
                        className="w-full bg-white/10 hover:bg-white/15 border border-white/10 text-white font-black text-xs uppercase tracking-widest py-4 rounded-xl transition-all"
                      >
                        Apply Directly
                      </button>

                      <button
                        onClick={() => setShowAiModal(false)}
                        className="text-text-muted hover:text-white text-xs font-bold py-2 transition"
                      >
                        Discard
                      </button>
                    </div>
                  </>
                ) : (
                  <div className="w-full text-left flex flex-col gap-4 animate-fade-in">
                    <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-1 text-center">Save Custom Template</h3>
                    
                    <div className="flex flex-col gap-1">
                      <label className="text-[10px] uppercase font-bold text-accent-green tracking-wider ml-1">Template Name</label>
                      <input 
                        type="text" 
                        value={ixiaTemplateName}
                        onChange={(e) => setIxiaTemplateName(e.target.value)}
                        placeholder="e.g. iXiA Hypertrophy PPL"
                        maxLength={50}
                        className="w-full bg-black border border-white/10 rounded-xl p-3 text-white text-sm outline-none focus:border-accent-green"
                      />
                    </div>
                    
                    <div className="flex flex-col gap-1">
                      <label className="text-[10px] uppercase font-bold text-accent-green tracking-wider ml-1">Description (Optional)</label>
                      <textarea 
                        value={ixiaTemplateDesc}
                        onChange={(e) => setIxiaTemplateDesc(e.target.value)}
                        placeholder="e.g. Routine auto-generated by iXiA AI"
                        maxLength={150}
                        className="w-full bg-black border border-white/10 rounded-xl p-3 text-white text-sm outline-none focus:border-accent-green h-20 resize-none"
                      />
                    </div>

                    <div className="w-full bg-[#111] border border-white/5 rounded-2xl p-4 text-left">
                      <label className="flex items-center gap-3 cursor-pointer select-none">
                        <input 
                          type="checkbox" 
                          checked={shouldDownloadBackup} 
                          onChange={(e) => setShouldDownloadBackup(e.target.checked)}
                          className="w-4 h-4 accent-accent-green"
                        />
                        <div className="flex flex-col">
                          <span className="text-xs font-bold text-white">Download Active Split Backup</span>
                          <span className="text-[9px] text-text-muted">Export current plan as .txt file first</span>
                        </div>
                      </label>
                    </div>

                    <div className="flex flex-col gap-2 mt-2">
                      <button 
                        onClick={() => handleSaveAiTemplate(true)}
                        className="w-full py-4 bg-[#2EEA82] text-black font-black text-xs uppercase tracking-widest rounded-xl transition-all active:scale-95 shadow-lg flex items-center justify-center gap-1"
                      >
                        Save & Apply Active
                      </button>
                      <button 
                        onClick={() => handleSaveAiTemplate(false)}
                        className="w-full py-4 bg-white/10 hover:bg-white/15 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all active:scale-95 border border-white/5"
                      >
                        Just Save
                      </button>
                      <button 
                        onClick={() => setIxiaSaveMode(false)}
                        className="text-text-muted hover:text-white text-xs font-bold text-center py-2 transition"
                      >
                        Back
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="p-8 relative z-10">
                <button 
                  onClick={() => setShowAiModal(false)}
                  className="absolute top-4 right-4 p-2 bg-white/5 rounded-full hover:bg-white/10 text-text-muted hover:text-white"
                >
                  <X className="w-4 h-4" />
                </button>
                
                <div className="flex flex-col items-center mb-8 mt-2 pointer-events-none">
                  <div className="w-16 h-16 mb-2">
                     <Orb hoverIntensity={0.1} rotateOnHover={true} forceHoverState={true} backgroundColor="transparent" />
                  </div>
                  <h2 className="text-xl font-black text-white">iXiA Ai Setup</h2>
                  <p className="text-[10px] text-text-muted font-bold tracking-widest uppercase mt-1">Smart Assistant is Ready</p>
                </div>

                <div className="flex flex-col gap-6">
                  {/* Goal Selection */}
                  <div className="flex flex-col gap-2">
                    <label className="text-[10px] uppercase font-bold text-[#2EEA82] tracking-widest ml-1">Main Goal</label>
                    <div className="flex flex-col gap-2">
                      {(['hypertrophy', 'strength', 'endurance'] as GoalType[]).map((g) => (
                        <button
                          key={g}
                          onClick={() => setGoal(g)}
                          className={`py-4 px-5 rounded-2xl text-xs font-bold transition-all border flex items-center justify-between ${
                            goal === g 
                              ? 'bg-[#2EEA82]/10 border-[#2EEA82] text-white shadow-[0_0_15px_rgba(46,234,130,0.1)]' 
                              : 'bg-white/5 border-white/5 text-text-muted hover:bg-white/10'
                          }`}
                        >
                          {g.charAt(0).toUpperCase() + g.slice(1)}
                          {goal === g && <div className="w-2 h-2 rounded-full bg-[#2EEA82]" />}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Split Selection */}
                  <div className="flex flex-col gap-2">
                    <label className="text-[10px] uppercase font-bold text-[#2EEA82] tracking-widest ml-1 mt-2">Preferred Split</label>
                    <div className="grid grid-cols-2 gap-2">
                      <button
                        onClick={() => setSplit('ppl')}
                        className={`py-3 rounded-xl text-xs font-bold transition-all border ${
                          split === 'ppl' ? 'bg-[#2EEA82]/10 border-[#2EEA82] text-white' : 'bg-white/5 border-white/5 text-text-muted'
                        }`}
                      >
                        Push/Pull/Legs
                      </button>
                      <button
                        onClick={() => setSplit('bro_split')}
                        className={`py-3 rounded-xl text-xs font-bold transition-all border ${
                          split === 'bro_split' ? 'bg-[#2EEA82]/10 border-[#2EEA82] text-white' : 'bg-white/5 border-white/5 text-text-muted'
                        }`}
                      >
                        Bro Split
                      </button>
                      <button
                        onClick={() => setSplit('upper_lower')}
                        className={`py-3 rounded-xl text-xs font-bold transition-all border ${
                          split === 'upper_lower' ? 'bg-[#2EEA82]/10 border-[#2EEA82] text-white' : 'bg-white/5 border-white/5 text-text-muted'
                        }`}
                      >
                        Upper/Lower
                      </button>
                      <button
                        onClick={() => setSplit('full_body')}
                        className={`py-3 rounded-xl text-xs font-bold transition-all border ${
                          split === 'full_body' ? 'bg-[#2EEA82]/10 border-[#2EEA82] text-white' : 'bg-white/5 border-white/5 text-text-muted'
                        }`}
                      >
                        Full Body
                      </button>
                    </div>
                  </div>

                  <button
                    onClick={handleGenerateAi}
                    className="w-full mt-4 bg-[#2EEA82] text-black font-black text-sm py-4 rounded-2xl shadow-[0_0_20px_rgba(46,234,130,0.3)] hover:shadow-[0_0_30px_rgba(46,234,130,0.5)] transition-all flex items-center justify-center gap-2"
                  >
                    GENERATE ROUTINE
                  </button>
                </div>
              </div>
            )}
            
          </div>
        </div>
      )}

      {/* View Workout Details Modal */}
      {selectedViewTemplate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in">
          <div className="w-full max-w-lg bg-[#111] border border-white/10 rounded-[2rem] p-6 relative flex flex-col max-h-[85vh] animate-fade-in-up shadow-2xl">
            
            {/* Header info - flex-shrink-0 keeps it from squishing day tabs and exercises list */}
            <div className="flex flex-col flex-shrink-0 relative mb-2">
              <button 
                onClick={() => setSelectedViewTemplate(null)}
                className="absolute top-0 right-0 p-2 bg-white/5 rounded-full hover:bg-white/10 text-text-muted hover:text-white"
              >
                <X className="w-4 h-4" />
              </button>
              
              <h3 className="text-lg font-black text-white pr-8">{selectedViewTemplate.name}</h3>
              <span className="text-[10px] text-accent-green uppercase font-bold tracking-widest mt-1 mb-2">{selectedViewTemplate.frequency}</span>
              <p className="text-xs text-text-muted mb-2 leading-relaxed">{selectedViewTemplate.description}</p>
            </div>
            
            {/* Horizontal Scrollable Day selector tabs - flex-shrink-0 protects layout structure */}
            <div className="flex gap-2 overflow-x-auto pb-3 mb-4 scrollbar-thin border-b border-white/5 flex-shrink-0">
              {selectedViewTemplate.plan.map((dayPlan) => (
                <button
                  key={dayPlan.day}
                  onClick={() => setActiveViewDay(dayPlan.day)}
                  className={`px-4 py-2 text-xs font-bold rounded-xl whitespace-nowrap transition-all ${
                    activeViewDay === dayPlan.day
                      ? 'bg-accent-green text-black font-black'
                      : 'bg-white/5 text-text-muted hover:text-white border border-white/5'
                  }`}
                >
                  {dayPlan.day} ({dayPlan.type})
                </button>
              ))}
            </div>
            
            {/* Exercises list - scrollable container */}
            <div className="flex-1 overflow-y-auto pr-1">
              {(() => {
                const currentDayPlan = selectedViewTemplate.plan.find(p => p.day === activeViewDay);
                if (!currentDayPlan) return null;
                
                if (currentDayPlan.type === 'Rest' || (currentDayPlan.warmups.length === 0 && currentDayPlan.mainLifts.length === 0)) {
                  return (
                    <div className="flex flex-col items-center justify-center py-10 text-text-muted">
                      <span className="text-3xl mb-2">😴</span>
                      <span className="text-xs font-bold">Rest / Recovery Day</span>
                      <span className="text-[10px] text-text-muted/60 mt-1">Focus on sleep, hydration, and active stretching.</span>
                    </div>
                  );
                }
                
                return (
                  <div className="flex flex-col gap-4">
                    {/* Warm-ups */}
                    {currentDayPlan.warmups.length > 0 && (
                      <div>
                        <span className="text-[9px] uppercase font-bold text-text-muted tracking-widest block mb-2">Warm-Up Protocol</span>
                        <div className="flex flex-col gap-2">
                          {currentDayPlan.warmups.map((ex) => (
                            <div key={ex.id} className="bg-white/5 border border-white/5 rounded-xl p-3">
                              <div className="flex justify-between items-start">
                                <span className="text-xs font-bold text-white">{ex.name}</span>
                                <span className="text-[10px] font-bold text-accent-green">{ex.targetSets} × {ex.targetValue}</span>
                              </div>
                              {ex.note && <p className="text-[10px] text-text-muted/80 mt-1 italic">Note: {ex.note}</p>}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                    
                    {/* Main Lifts */}
                    {currentDayPlan.mainLifts.length > 0 && (
                      <div>
                        <span className="text-[9px] uppercase font-bold text-accent-green tracking-widest block mb-2">Main Lifts</span>
                        <div className="flex flex-col gap-2">
                          {currentDayPlan.mainLifts.map((ex) => (
                            <div key={ex.id} className="bg-white/5 border border-white/5 rounded-xl p-3">
                              <div className="flex justify-between items-start">
                                <span className="text-xs font-bold text-white">{ex.name}</span>
                                <span className="text-[10px] font-bold text-accent-green">{ex.targetSets} × {ex.targetValue} {ex.trackingType === 'time_only' ? '' : 'reps'}</span>
                              </div>
                              {ex.note && <p className="text-[10px] text-text-muted/80 mt-1 italic">Note: {ex.note}</p>}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })()}
            </div>
            
            {/* Modal Actions - flex-shrink-0 keeps it visible at bottom */}
            <div className="mt-6 pt-4 border-t border-white/5 flex gap-3 flex-shrink-0">
              <button
                onClick={() => setSelectedViewTemplate(null)}
                className="flex-1 py-3 bg-white/5 hover:bg-white/10 text-white font-bold text-xs uppercase tracking-widest rounded-xl transition-all border border-white/5"
              >
                Close
              </button>
              <button
                onClick={() => {
                  const id = selectedViewTemplate.id;
                  setSelectedViewTemplate(null);
                  handleApplyTemplate(id);
                }}
                disabled={appliedId !== null}
                className="flex-1 py-3 bg-accent-green text-black font-black text-xs uppercase tracking-widest rounded-xl transition-all shadow-lg active:scale-95"
              >
                APPLY THIS PLAN
              </button>
            </div>
            
          </div>
        </div>
      )}
      
    </main>
  );
}
