INSERT INTO exercises (id, name, muscle_group, category) VALUES
(gen_random_uuid(), 'Bench Press', 'chest', 'strength'),
(gen_random_uuid(), 'Incline Bench Press', 'chest', 'strength'),
(gen_random_uuid(), 'Decline Bench Press', 'chest', 'strength'),
(gen_random_uuid(), 'Push-up', 'chest', 'strength'),
(gen_random_uuid(), 'Dumbbell Fly', 'chest', 'strength'),
(gen_random_uuid(), 'Cable Crossover', 'chest', 'strength'),
(gen_random_uuid(), 'Pec Deck Machine', 'chest', 'strength'),
(gen_random_uuid(), 'Chest Dip', 'chest', 'strength'),
(gen_random_uuid(), 'Pullover', 'chest', 'strength'),
(gen_random_uuid(), 'Floor Press', 'chest', 'strength'),
(gen_random_uuid(), 'Machine Chest Press', 'chest', 'strength'),
(gen_random_uuid(), 'Svend Press', 'chest', 'strength'),
(gen_random_uuid(), 'Deficit Push-up', 'chest', 'strength'),
(gen_random_uuid(), 'Spiderman Push-up', 'chest', 'strength'),
(gen_random_uuid(), 'Close-Grip Bench Press', 'chest', 'strength'),
(gen_random_uuid(), 'Pull-up', 'back', 'strength'),
(gen_random_uuid(), 'Chin-up', 'back', 'strength'),
(gen_random_uuid(), 'Barbell Row', 'back', 'strength'),
(gen_random_uuid(), 'Dumbbell Row', 'back', 'strength'),
(gen_random_uuid(), 'Lat Pulldown', 'back', 'strength'),
(gen_random_uuid(), 'Seated Cable Row', 'back', 'strength'),
(gen_random_uuid(), 'T-Bar Row', 'back', 'strength'),
(gen_random_uuid(), 'Deadlift', 'back', 'strength'),
(gen_random_uuid(), 'Rack Pull', 'back', 'strength'),
(gen_random_uuid(), 'Good Morning', 'back', 'strength'),
(gen_random_uuid(), 'Hyperextension', 'back', 'strength'),
(gen_random_uuid(), 'Straight-Arm Pulldown', 'back', 'strength'),
(gen_random_uuid(), 'Machine Row', 'back', 'strength'),
(gen_random_uuid(), 'Meadows Row', 'back', 'strength'),
(gen_random_uuid(), 'Pendlay Row', 'back', 'strength'),
(gen_random_uuid(), 'Renegade Row', 'back', 'strength'),
(gen_random_uuid(), 'Face Pull', 'back', 'strength'),
(gen_random_uuid(), 'Superman', 'back', 'strength'),
(gen_random_uuid(), 'Squat', 'legs', 'strength'),
(gen_random_uuid(), 'Front Squat', 'legs', 'strength'),
(gen_random_uuid(), 'Leg Press', 'legs', 'strength'),
(gen_random_uuid(), 'Lunge', 'legs', 'strength'),
(gen_random_uuid(), 'Bulgarian Split Squat', 'legs', 'strength'),
(gen_random_uuid(), 'Romanian Deadlift', 'legs', 'strength'),
(gen_random_uuid(), 'Stiff-Leg Deadlift', 'legs', 'strength'),
(gen_random_uuid(), 'Leg Extension', 'legs', 'strength'),
(gen_random_uuid(), 'Leg Curl', 'legs', 'strength'),
(gen_random_uuid(), 'Calf Raise', 'legs', 'strength'),
(gen_random_uuid(), 'Seated Calf Raise', 'legs', 'strength'),
(gen_random_uuid(), 'Goblet Squat', 'legs', 'strength'),
(gen_random_uuid(), 'Hack Squat', 'legs', 'strength'),
(gen_random_uuid(), 'Glute Bridge', 'legs', 'strength'),
(gen_random_uuid(), 'Hip Thrust', 'legs', 'strength'),
(gen_random_uuid(), 'Step-up', 'legs', 'strength'),
(gen_random_uuid(), 'Sissy Squat', 'legs', 'strength'),
(gen_random_uuid(), 'Pistol Squat', 'legs', 'strength'),
(gen_random_uuid(), 'Sumo Deadlift', 'legs', 'strength'),
(gen_random_uuid(), 'Box Jump', 'legs', 'strength'),
(gen_random_uuid(), 'Barbell Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Dumbbell Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Hammer Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Preacher Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Concentration Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Cable Curl', 'arms', 'strength'),
(gen_random_uuid(), 'EZ-Bar Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Triceps Pushdown', 'arms', 'strength'),
(gen_random_uuid(), 'Overhead Triceps Extension', 'arms', 'strength'),
(gen_random_uuid(), 'Skull Crusher', 'arms', 'strength'),
(gen_random_uuid(), 'Triceps Dip', 'arms', 'strength'),
(gen_random_uuid(), 'Triceps Kickback', 'arms', 'strength'),
(gen_random_uuid(), 'Diamond Push-up', 'arms', 'strength'),
(gen_random_uuid(), 'Zottman Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Reverse Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Wrist Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Reverse Wrist Curl', 'arms', 'strength'),
(gen_random_uuid(), 'Overhead Press', 'shoulders', 'strength'),
(gen_random_uuid(), 'Dumbbell Shoulder Press', 'shoulders', 'strength'),
(gen_random_uuid(), 'Arnold Press', 'shoulders', 'strength'),
(gen_random_uuid(), 'Lateral Raise', 'shoulders', 'strength'),
(gen_random_uuid(), 'Front Raise', 'shoulders', 'strength'),
(gen_random_uuid(), 'Reverse Pec Deck', 'shoulders', 'strength'),
(gen_random_uuid(), 'Upright Row', 'shoulders', 'strength'),
(gen_random_uuid(), 'Shrug', 'shoulders', 'strength'),
(gen_random_uuid(), 'Push Press', 'shoulders', 'strength'),
(gen_random_uuid(), 'Cable Lateral Raise', 'shoulders', 'strength'),
(gen_random_uuid(), 'Machine Shoulder Press', 'shoulders', 'strength'),
(gen_random_uuid(), 'High Pull', 'shoulders', 'strength'),
(gen_random_uuid(), 'Farmer''s Walk', 'shoulders', 'strength'),
(gen_random_uuid(), 'Crunch', 'core', 'strength'),
(gen_random_uuid(), 'Plank', 'core', 'strength'),
(gen_random_uuid(), 'Russian Twist', 'core', 'strength'),
(gen_random_uuid(), 'Hanging Leg Raise', 'core', 'strength'),
(gen_random_uuid(), 'Bicycle Crunch', 'core', 'strength'),
(gen_random_uuid(), 'Ab Wheel Rollout', 'core', 'strength'),
(gen_random_uuid(), 'Sit-up', 'core', 'strength'),
(gen_random_uuid(), 'V-up', 'core', 'strength'),
(gen_random_uuid(), 'Flutter Kicks', 'core', 'strength'),
(gen_random_uuid(), 'Mountain Climber', 'core', 'strength'),
(gen_random_uuid(), 'Dead Bug', 'core', 'strength'),
(gen_random_uuid(), 'Cable Crunch', 'core', 'strength'),
(gen_random_uuid(), 'Reverse Crunch', 'core', 'strength'),
(gen_random_uuid(), 'Side Plank', 'core', 'strength'),
(gen_random_uuid(), 'Toes to Bar', 'core', 'strength'),
(gen_random_uuid(), 'L-Sit', 'core', 'strength')
ON CONFLICT (id) DO NOTHING;
